---
- name: create vpc full structure
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: create a VPC
      ec2_vpc_net:
        name: Ansible_VPC
        cidr_block: 10.20.10.0/24
        region: us-east-1  # Specify your desired AWS region
        tags:
          Name: Ansible_VPC
      register: vpc_result

    - name: Set fact for VPC ID
      set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"
      register: vpcid

    - name: Display VPC id
      debug:
        var: vpc_result.vpc.id
    
    - name: save VPC id to a file
      copy:
        content: "{{ vpc_result.vpc.id }}"
        dest: /home/ansadmin/ansibleplaybook/output/vpc_id.txt


    - name: Create public Subnet 1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc_id }}"
        cidr: 10.20.10.0/25
        map_public : true
        region: us-east-1  # Specify the same AWS region
        tags:
          Name: public_subnet_1
      register: public_subnet_result

    - name: save public Subnet id to a file
      copy:
        content: "{{ public_subnet_result.subnet.id }}"
        dest: /home/ansadmin/ansibleplaybook/output/pub_sn_id.txt

    - name: Create Private subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: 10.20.10.128/25
        region: us-east-1  # Specify the same AWS region
        tags:
          Name: private_subnet_1
      register: private_subnet_result
    
    - name: save private Subnet id to a file
      copy:
        content: "{{ private_subnet_result.subnet.id }}"
        dest: /home/ansadmin/ansibleplaybook/output/priv_sn_id.txt

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        state: present
        region: us-east-1  # Specify the same AWS region
        tags:
          Name: MyIGW
      register: igw_result

    - name: Display the IGW id
      debug:
        var: igw_result.gateway_id    
    
    - name: create Public Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: us-east-1
        tags:
          Name: Public_router
        subnets:
          - "{{ public_subnet_result.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id }}"
          - dest: ::/0
            gateway_id: "{{ igw_result.gateway_id }}"
    
    - name: create private Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: us-east-1
        tags:
          Name: private_router
        subnets:
          - "{{ private_subnet_result.subnet.id }}"
    
    - name: example using security group rule descriptions
      amazon.aws.ec2_security_group:
        name: ansible-sg
        description: ansible-sg
        vpc_id: "{{ vpc_id }}"
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80
            - 22
            - 8080
            cidr_ip: 0.0.0.0/0
      register: ansible_sg_result

    - name: Display the Security Group
      debug:
        var: ansible_sg_result.group_id
    
    - name: Nat security group creating
      amazon.aws.ec2_security_group:
        name: nat-sg
        description: ansible-sg
        vpc_id: "{{ vpc_id }}"
        region: us-east-1
        rules:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: nat_sg_result

    - name: Display the Security Group
      debug:
        var: ansible_sg_result.group_id
    
    - name: ec2 creation
      amazon.aws.ec2_instance:
        name: "Public_instance"
        key_name: "AWS_FREE_PAIR"
        vpc_subnet_id: "{{ public_subnet_result.subnet.id }}"
        instance_type: t2.micro
        security_group: "{{ ansible_sg_result.group_id }}"
        volumes:    
          - device_name: /dev/sda1
            ebs:
              volume_size: 8
              volume_type: gp3
        network:
          assign_public_ip: true
        tags:
          Name: Public_instance
          os: ubuntu
        image_id: ami-053b0d53c279acc90
      register: public_instance
    
    - name: ec2 creation = nat instance
      amazon.aws.ec2_instance:
        name: "nat_instance"
        key_name: "AWS_FREE_PAIR"
        vpc_subnet_id: "{{ public_subnet_result.subnet.id }}"
        instance_type: t2.micro
        security_group: "{{ ansible_sg_result.group_id }}"
        volumes:    
          - device_name: /dev/sda1
            ebs:
              volume_size: 8
              volume_type: gp3
        network:
          assign_public_ip: true
        tags:
          Name: nat_instance
          os: ubuntu
        image_id: ami-0822796fd7b3ba710
      register: nat_instance_result
    
    - name: ec2 creation = nat instance
      amazon.aws.ec2_instance:
        name: "nat_instance"
        key_name: "AWS_FREE_PAIR"
        vpc_subnet_id: "{{ public_subnet_result.subnet.id }}"
        instance_type: t2.micro
        security_group: "{{ nat_sg_result.group_id }}"
        volumes:    
          - device_name: /dev/sda1
            ebs:
              volume_size: 8
              volume_type: gp3
        network:
          assign_public_ip: true
        tags:
          Name: nat_instance
          os: nat
        image_id: ami-0822796fd7b3ba710
      register: nat_instance_result

    - name: ec2 creation = private instance
      amazon.aws.ec2_instance:
        name: "private_instance"
        key_name: "AWS_FREE_PAIR"
        vpc_subnet_id: "{{ private_subnet_result.subnet.id }}"
        instance_type: t2.micro
        security_group: "{{ ansible_sg_result.group_id }}"
        volumes:    
          - device_name: /dev/sda1
            ebs:
              volume_size: 8
              volume_type: gp3
        network:
          assign_public_ip: false
        tags:
          Name: private_instance
          os: nat
        image_id: ami-0822796fd7b3ba710
      register: private_instance_result



    
        
    