---
- name: Install and configure Apache HTTP Server
  hosts: tag_Os_amazonlinux  # Define the target servers or group in your inventory file
  become: yes  # Run tasks with sudo or as root

  tasks:
    - name: Update package cache
      yum:
        name: '*httpd*'
        state: latest
      tags:
        - update

    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: present
      tags:
        - install

    - name: Start Apache and enable it at boot
      service:
        name: httpd
        state: started
        enabled: yes
      tags:
        - start
    - name: Allow HTTP traffic through the firewall (if needed)
      firewalld:
        service: http
        permanent: yes
        state: enabled
      tags:
        - configure

    - name: Reload firewalld (if needed)
      service:
        name: firewalld
        state: reloaded
      tags:
        - configure

  handlers:
    - name: Restart Apache if configuration changes
      service:
        name: httpd
        state: restarted

