---
- name: Create EC2 instance with Nginx
  hosts: localhost
  gather_facts: yes  
  
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "private_instance-1"
        key_name: "AWS_FREE_PAIR"
        vpc_subnet_id: subnet-06a438c50cb2fa0e7
        instance_type: t2.micro
        security_group: all_traffic
        network:
          assign_public_ip: false
        image_id: ami-053b0d53c279acc90
        tags:
          os: ubuntu
      register: ec2_instance  


    - name: screening ec2 creation
      debug:
        var: ec2_instance.instances[0].private_ip_address

    
