---
- name: create vpc full structure
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: create a VPC
      ec2_vpc_net:
        name: Ansible_VPC
        cidr_block: 10.20.10.0/24
        region: us-east-1  # Specify your desired AWS region
        tags:
          Name: Ansible_VPC
      register: vpc_result

    - name: Set fact for VPC ID
      set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"
      register: vpcid

    - name: Display VPC id
      debug:
        var: vpc_result.vpc.id

    - name: Create public Subnet 1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc_id }}"
        cidr: 10.20.10.0/25
        map_public : true
        region: us-east-1  # Specify the same AWS region
        tags:
          Name: public_subnet_1
      register: public_subnet_result

    - name: Create Private subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: 10.20.10.128/25
        region: us-east-1  # Specify the same AWS region
        tags:
          Name: private_subnet_1
      register: private_subnet_result

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        state: present
        region: us-east-1  # Specify the same AWS region
        tags:
          Name: MyIGW
      register: igw_result

    - name: Display the IGW id
      debug:
        var: igw_result.gateway_id    
    
    - name: create Public Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: us-east-1
        tags:
          Name: Public_router
        subnets:
          - "{{ public_subnet_result.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id }}"
          - dest: ::/0
            gateway_id: "{{ igw_result.gateway_id }}"
          - dest: 172.31.80.0/20
            gateway_id: pcx-0d54de6acad6dbb20
    
    - name: create private Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: us-east-1
        tags:
          Name: private_router
        subnets:
          - "{{ private_subnet_result.subnet.id }}"
    
    